### PR TITLE
Fix pinnings and rerender

### PR DESCRIPTION
**Pull request by SylvainCorlay**

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
@chrisburr it seems that the root patches are breaking xeus-cling.

**Comment by SylvainCorlay** [comment]
Is it possible to remove the patch:

https://github.com/conda-forge/clangdev-feedstock/blob/5.x/recipe/root-patches/0005-refactor-in-RequireCompleteDeclContext.patch

**Comment by SylvainCorlay** [comment]
Other build failing due to the root patch: https://github.com/QuantStack/xeus-cling/pull/215

**Comment by SylvainCorlay** [comment]
My bad, a new build of cling using that should not require that symbol anymore.

**Comment by SylvainCorlay** [comment]
The new failure on OSX appears to be due to the `llvm` package from default being pulled, which overrides some cmake files from llvmdev.

**Comment by chrisburr** [comment]
> The new failure on OSX appears to be due to the `llvm` package from default being pulled, which overrides some cmake files from llvmdev.

The failure is because the mac OS compilers are being pulled in at run time and they conflict with `llvmdev`.

**Comment by SylvainCorlay** [comment]
Yes I just pushed a new commit to the cli g feedstock to remove the runtime dep on os x.

**Comment by saraedum** [comment]
Something broke with this change, see https://github.com/QuantStack/xeus-cling/issues/194#issuecomment-456547091. Or am I doing something wrong?

**Comment by chrisburr** [comment]
This should be fixed once https://github.com/conda-forge/clangdev-feedstock/pull/45 is finished. See https://github.com/conda-forge/root-feedstock/issues/2 for more details.

**Pull request merged**
